name: Set project version
inputs:
  file:
    description: path to .csproj
    required: true
outputs:
  version:
    description: version set to ${{ inputs.file }}
    value: ${{ steps.set.outputs.value }}
runs:
  using: composite
  steps:
  - id: set
    name: Set project version to ${{ inputs.file }}
    shell: bash
    run: |-
      csproj-version set --version ${{ inputs.version }} ${{ inputs.file }}
      echo "value=$(csproj-version get ${{ inputs.file }})" >> $GITHUB_OUTPUT
