name: Set project version
inputs:
  file:
    description: path to .csproj
    required: true
  version:
    description: version in SemVer format
    required: true
  xpath:
    description: XPath to version element
    required: false
    default: '//PropertyGroup/Version'
  regex:
    description: ECMAScript Regular Expression to parse the version string for verification
    required: false
    default: '^(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)(\\.(?<patch>0|[1-9]\\d*))?(?:-(?<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$'
outputs:
  version:
    description: version set to inputs.file
    value: ${{ steps.set.outputs.value }}
runs:
  using: composite
  steps:
  - id: set
    name: Set project version to ${{ inputs.file }}
    shell: bash
    run: |-
      csproj-version set --version ${{ inputs.version }} --xpath ${{ inputs.xpath }} --regex ${{ inputs.regex }} ${{ inputs.file }}
      echo "value=$(csproj-version set --version ${{ inputs.version }} --xpath ${{ inputs.xpath }} --regex ${{ inputs.regex }} ${{ inputs.file }})" >> $GITHUB_OUTPUT
