name: Get project version
inputs:
  file:
    description: path to .csproj
    required: true
outputs:
  version:
    description: version retrieved from inputs.file
    value: ${{ steps.get.outputs.version }}
runs:
  using: composite
  steps:
  - id: get
    name: Get project version from ${{ inputs.file }}
    shell: bash
    run: |-
      csproj-version get ${{ inputs.file }}
      echo "version=$(csproj-version get ${{ inputs.file }})" >> $GITHUB_OUTPUT
